# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789ff16a9ba78f05854102e8e8f1108cd01fb506d6368686cae56462019fc0bfcf1a0ad29053572dd326281b3197fbf0f6d66b2f5cd7dbbf9ece5fb9783ab13d

test:
  secret_key_base: 63bb3d12262924287704962c64c61b19657a4a8a29ad17d64f61dd1e55a453888e08fcdcec5609890fcf8d72eb092fb1fee6ea10cf51493732d24265fb4d37ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
